# Generated by Django 4.1.1 on 2022-09-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0002_item_currency_item_description_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Корзина для сессии', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Корзина для сессии'),
        ),
    ]
